apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
data:
  # base64 encoding of 'root'
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  # base64 encoding of 'example'
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==